"""add_decision_logs

Revision ID: 730f6cb52035
Revises: c3d4e5f6a7b8
Create Date: 2026-03-20 10:27:25.986278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '730f6cb52035'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('final_confidence', sa.Integer(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('executed', sa.Boolean(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('tech_direction', sa.String(length=10), nullable=False),
    sa.Column('tech_confidence', sa.Integer(), nullable=False),
    sa.Column('tech_rsi', sa.Float(), nullable=True),
    sa.Column('tech_ema_fast', sa.Float(), nullable=True),
    sa.Column('tech_ema_slow', sa.Float(), nullable=True),
    sa.Column('tech_macd', sa.Float(), nullable=True),
    sa.Column('tech_macd_hist', sa.Float(), nullable=True),
    sa.Column('tech_atr', sa.Float(), nullable=True),
    sa.Column('tech_volume_ratio', sa.Float(), nullable=True),
    sa.Column('tech_price', sa.Float(), nullable=True),
    sa.Column('tech_ema_crossover', sa.String(length=10), nullable=True),
    sa.Column('tech_macd_crossover', sa.String(length=10), nullable=True),
    sa.Column('tech_rsi_extreme', sa.String(length=12), nullable=True),
    sa.Column('candles_used', sa.Integer(), nullable=False),
    sa.Column('sentiment_label', sa.String(length=10), nullable=False),
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('sentiment_impact', sa.Integer(), nullable=False),
    sa.Column('sentiment_source', sa.String(length=20), nullable=False),
    sa.Column('sentiment_news_count', sa.Integer(), nullable=False),
    sa.Column('sentiment_modifier', sa.Float(), nullable=False),
    sa.Column('risk_approved', sa.Boolean(), nullable=True),
    sa.Column('risk_position_size', sa.Float(), nullable=True),
    sa.Column('risk_stop_loss', sa.Float(), nullable=True),
    sa.Column('risk_take_profit', sa.Float(), nullable=True),
    sa.Column('risk_rr_ratio', sa.Float(), nullable=True),
    sa.Column('risk_sizing_method', sa.String(length=15), nullable=True),
    sa.Column('risk_rejection', sa.Text(), nullable=True),
    sa.Column('reasons', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_logs_decided_at'), 'decision_logs', ['decided_at'], unique=False)
    op.create_index(op.f('ix_decision_logs_portfolio_id'), 'decision_logs', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_decision_logs_symbol'), 'decision_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_decision_logs_user_id'), 'decision_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_logs_user_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_symbol'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_portfolio_id'), table_name='decision_logs')
    op.drop_index(op.f('ix_decision_logs_decided_at'), table_name='decision_logs')
    op.drop_table('decision_logs')
    # ### end Alembic commands ###
