"""sync_check

Revision ID: e0e42083b521
Revises: a3b4c5d6e7f8
Create Date: 2026-03-23 14:05:16.999658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0e42083b521'
down_revision: Union[str, None] = 'a3b4c5d6e7f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bot_states_user_id_key'), 'bot_states', type_='unique')
    op.alter_column('daily_performance_summaries', 'total_trades',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_performance_summaries', 'winning_trades',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_performance_summaries', 'losing_trades',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('daily_performance_summaries', 'win_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('daily_performance_summaries', 'total_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=False)
    op.alter_column('daily_performance_summaries', 'avg_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=False)
    op.alter_column('daily_performance_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_performance_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_daily_performance_summaries_portfolio_id'), 'daily_performance_summaries', ['portfolio_id'], unique=False)
    op.drop_index(op.f('ix_historical_event_currency'), table_name='historical_events')
    op.create_index(op.f('ix_historical_events_currency'), 'historical_events', ['currency'], unique=False)
    op.drop_index(op.f('ix_market_price_symbol'), table_name='market_prices')
    op.create_index(op.f('ix_market_prices_symbol'), 'market_prices', ['symbol'], unique=False)
    op.drop_index(op.f('ix_perf_snap_captured_at'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_perf_snap_portfolio_id'), table_name='performance_snapshots')
    op.create_index(op.f('ix_performance_snapshots_captured_at'), 'performance_snapshots', ['captured_at'], unique=False)
    op.create_index(op.f('ix_performance_snapshots_portfolio_id'), 'performance_snapshots', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_snapshots_portfolio_id'), table_name='performance_snapshots')
    op.drop_index(op.f('ix_performance_snapshots_captured_at'), table_name='performance_snapshots')
    op.create_index(op.f('ix_perf_snap_portfolio_id'), 'performance_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_perf_snap_captured_at'), 'performance_snapshots', ['captured_at'], unique=False)
    op.drop_index(op.f('ix_market_prices_symbol'), table_name='market_prices')
    op.create_index(op.f('ix_market_price_symbol'), 'market_prices', ['symbol'], unique=False)
    op.drop_index(op.f('ix_historical_events_currency'), table_name='historical_events')
    op.create_index(op.f('ix_historical_event_currency'), 'historical_events', ['currency'], unique=False)
    op.drop_index(op.f('ix_daily_performance_summaries_portfolio_id'), table_name='daily_performance_summaries')
    op.alter_column('daily_performance_summaries', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_performance_summaries', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('daily_performance_summaries', 'avg_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=True)
    op.alter_column('daily_performance_summaries', 'total_pnl',
               existing_type=sa.NUMERIC(precision=18, scale=4),
               nullable=True)
    op.alter_column('daily_performance_summaries', 'win_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('daily_performance_summaries', 'losing_trades',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_performance_summaries', 'winning_trades',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('daily_performance_summaries', 'total_trades',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(op.f('bot_states_user_id_key'), 'bot_states', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
